name: image-anonymisation
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py
  - jupyter
  - matplotlib
  - mkl
  - numpy
  - pandas
  - pip
  - prettytable
  - python=3.7
  - scikit-learn
  - scipy
  - tqdm
  - tensorflow-gpu=1.15.0
  - pip:
    - pillow